Update README.md
Python 3.11 is required; running with Python 3.10 results in an error like this:

```
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' 
```